application_api_version: v1beta1
properties:
  name:
    type: string
    default: conjur
    x-google-marketplace:
      type: NAME
  namespace:
    type: string
    x-google-marketplace:
      type: NAMESPACE
  conjur.image:
    type: string
    default: $REGISTRY/cyberark:$TAG
    x-google-marketplace:
      type: IMAGE
  postgres.image:
    type: string
    default: $REGISTRY/cyberark/postgres:$TAG
    x-google-marketplace:
      type: IMAGE
  conjur.dataKey:
    type: string
    title: Conjur Data key
    description: Encryption key for Conjur database.
    x-google-marketplace:
      type: GENERATED_PASSWORD
      generatedPassword:
        length: 32
        base64: true
  conjur.databaseUrl:
    type: string
    title: External PostgreSQL connection (Optional)
    description: >-
      PostgreSQL connection string for Conjur. If none is provided, a Postgres
      deployment will be created for you

required:
- name
- namespace
- conjur.image
- postgres.image
- conjur.dataKey
