x-google-marketplace:
  schemaVersion: v2

  # Must match the version of the Application custom resource object.
  applicationApiVersion: v1beta1

  # The release version must match the release tag on the deployer
  publishedVersion: '1.4.0'

  publishedVersionMetadata:
    releaseNote: >-
      Update marketplace tools so app works with Kubernetes version >= 1.16.

    # If "recommended" is "true", users using older releases are encouraged
    # to update as soon as possible. This is useful if, for example, this
    # release fixes a critical issue.
    recommended: true

  # This MUST be specified to indicate that the deployer supports managed
  # updates. Note that this could be left out or kalmSupported set to false,
  # in which case the deployer uses schema v2 but does not support updates.
  managedUpdates:
    kalmSupported: false

  images:
    postgres:
      properties:
        imageRepo:
          type: REPO_WITH_REGISTRY
        imageTag:
          type: TAG
    nginx:
      properties:
        imageRepo:
          type: REPO_WITH_REGISTRY
        imageTag:
          type: TAG
    init:
      properties:
        imageInitFull:
          type: FULL
        imageInitRegistry:
          type: REGISTRY
        imageInitRepo:
          type: REPO_WITHOUT_REGISTRY
        imageInitTag:
          type: TAG

  clusterConstraints:
    resources:
    - requests:
        cpu: 1000m
        memory: 3750Mi
      affinity:
        simpleNodeAffinity:
          type: REQUIRE_MINIMUM_NODE_COUNT
          minimumNodeCount: 3

properties:
  name:
    type: string
    default: conjur
    x-google-marketplace:
      type: NAME
  namespace:
    type: string
    x-google-marketplace:
      type: NAMESPACE
  conjur-oss.account:
    type: string
    default: default
    title: Conjur Account
    description: >-
      If using the Conjur authenticator for Kubernetes, an account name must be
      specified. This allows for authentication of roles under the given account.
      Note that this field is strictly a reference; it will not create an account.
  conjur-oss.authenticators:
    type: string
    default: authn
    title: Conjur Authenticators
    description: >-
      Comma-separated list of authenticators to enable on Conjur.
      See the full list at https://docs.conjur.org/Latest/en/Content/Operations/Services/authentication-types.htm.
  conjur-oss.dataKey:
    type: string
    title: Conjur Data key
    description: Encryption key for Conjur database.
    x-google-marketplace:
      type: GENERATED_PASSWORD
      generatedPassword:
        length: 32
        base64: true
  conjur-oss.databaseUrl:
    type: string
    title: External PostgreSQL connection (Optional)
    description: >-
      PostgreSQL connection string for Conjur. If none is provided, a Postgres
      deployment will be created for you. This value is stored in a Kubernetess secret.
  conjur-oss.persistentVolumeSize:
    type: string
    default: 8Gi
    title: Storage
    description: Size of disk to be used for persistent PostgreSQL database
  conjur-oss.ssl.expiration:
    type: integer
    title: Certificate Expiration (days)
    default: 365
    minimum: 1
  conjur-oss.ssl.hostname:
    type: string
    title: Certificate Common Name
    description: The external DNS which will be used as the endpoint for the Conjur instance.
  conjur-oss.serviceAccount.name:
    type: string
    x-google-marketplace:
      type: SERVICE_ACCOUNT
      serviceAccount:
        roles:
        - type: ClusterRole
          rulesType: CUSTOM
          rules:
          - apiGroups: [""]
            resources: ["pods", "serviceaccounts"]
            verbs: ["get", "list"]
          - apiGroups: ["extensions"]
            resources: [ "deployments", "replicasets"]
            verbs: ["get", "list"]
          - apiGroups: ["apps"]
            resources: [ "deployments", "statefulsets", "replicasets"]
            verbs: ["get", "list"]
          - apiGroups: [""]
            resources: ["pods/exec"]
            verbs: ["create", "get"]

required:
- name
- namespace
- conjur-oss.dataKey
- conjur-oss.persistentVolumeSize
- conjur-oss.ssl.expiration
- conjur-oss.ssl.hostname
- conjur-oss.serviceAccount.name
