application_api_version: v1beta1
properties:
  name:
    type: string
    default: conjur
    x-google-marketplace:
      type: NAME
  namespace:
    type: string
    x-google-marketplace:
      type: NAMESPACE
  imageConjur:
    type: string
    default: $REGISTRY/cyberark:$TAG
    x-google-marketplace:
      type: IMAGE
  imagePostgres:
    type: string
    default: $REGISTRY/cyberark/postgres:$TAG
    x-google-marketplace:
      type: IMAGE
  conjurDataKey:
    type: string
    title: Conjur Data key
    description: Encryption key for Conjur database.
    x-google-marketplace:
      type: GENERATED_PASSWORD
      generatedPassword:
        length: 32
  conjurDatabaseUrl:
    type: string
    title: PostgreSQL connection
    description: PostgreSQL connection string for Conjur.
    default: "postgres://postgres@postgres/postgres"
    x-google-marketplace:
      type: STRING
      string:
        generatedProperties:
          base64Encoded: conjurDatabaseUrlEncoded
required:
- name
- namespace
- imageConjur
- conjurDataKey
- conjurDatabaseUrl
