application_api_version: v1beta1
properties:
  name:
    type: string
    default: conjur
    x-google-marketplace:
      type: NAME
  namespace:
    type: string
    x-google-marketplace:
      type: NAMESPACE
  conjur.image:
    type: string
    default: $REGISTRY/cyberark:$TAG
    x-google-marketplace:
      type: IMAGE
      image:
        generatedProperties:
          splitByColon:
            before: image.repository
            after: image.tag
  postgres.image:
    type: string
    default: $REGISTRY/cyberark/postgres:$TAG
    x-google-marketplace:
      type: IMAGE
      image:
        generatedProperties:
          splitByColon:
            before: postgres.repository
            after: postgres.tag
  conjuross.authenticators:
    type: string
    default: authn
    title: Conjur Authenticators
    description: >-
      Comma-separated list of authenticators to enable on Conjur.
      See the full list at https://docs.conjur.org/Latest/en/Content/Operations/Services/authentication-types.htm.
  conjuross.dataKey:
    type: string
    title: Conjur Data key
    description: Encryption key for Conjur database.
    x-google-marketplace:
      type: GENERATED_PASSWORD
      generatedPassword:
        length: 32
        base64: true
  conjuross.databaseUrl:
    type: string
    title: External PostgreSQL connection (Optional)
    description: >-
      PostgreSQL connection string for Conjur. If none is provided, a Postgres
      deployment will be created for you. This value is stored in a Kubernetess secret.

required:
- name
- namespace
- conjur.image
- postgres.image
- conjuross.dataKey
