properties:
  name:
    type: ​string
    x-google-marketplace:
      type: ​NAME
  namespace:
    type: ​string
    x-google-marketplace:
      type: ​NAMESPACE
  Image:
    type: ​string
    default: ​gcr.io/conjur-cloud-launcher-onboard/cyberark/conjur:latest
    x-google-marketplace:
      type: ​IMAGE
  serverReplicas:
    title: ​Server​ ​replicas
    type: ​int
    default: 1
    minimum: 1
  blogTitle:
    title: ​Blog​ ​title
    description: ​WordPress​ ​requires​ ​a​ ​blog​ ​title​ ​for​ ​setup.​ ​This​ ​can​ ​be changed​ ​later.
    type: ​string
    maxLength: 128
    pattern: ​'[A-Za-z0-9 -]+'
required:
-​ ​name
-​ ​namespace
-​ Image
-​ ​serveReplicas
-​ ​blogTitle