properties:
  name:
    type: string
    x-google-marketplace:
      type: NAME
  namespace:
    type: string
    x-google-marketplace:
      type: NAMESPACE
  image:
    type: string
    default: gcr.io/conjur-cloud-launcher-onboard/cyberark/conjur:latest
    x-google-marketplace:
      type: IMAGE
required:
- name
- namespace
- image