# This schema file defines any properties and/or property defaults that
# are required for testing that are not otherwise defined in the
# application schema.yaml file in the project root directory.
# (i.e. Properties from these two schema.yaml files are combined for testing.)
x-google-marketplace:
  schemaVersion: v2

  images:
    tester:
      properties:
        imageTester:
          type: FULL
          default: $REGISTRY/tester:$TAG

properties:
  tester.image:
    type: string
    default: $REGISTRY/tester:$TAG

  conjur-oss.ssl.hostname:
    type: string
    default: "$CERTIFICATE_CN"
    title: Certificate Common Name
