x-google-marketplace:
  schemaVersion: v2

  # Must match the version of the Application custom resource object.
  applicationApiVersion: v1beta1

  # The release version must match the release tag on the deployer
  publishedVersion: '1.4.0'

  images:
    postgres:
      properties:
        imageRepo:
          type: REPO_WITH_REGISTRY
        imageTag:
          type: TAG
    nginx:
      properties:
        imageRepo:
          type: REPO_WITH_REGISTRY
        imageTag:
          type: TAG
    tester:
      properties:
        imageRepo:
          type: REPO_WITH_REGISTRY
        imageTag:
          type: TAG
    init:
      properties:
        imageInitFull:
          type: FULL
        imageInitRegistry:
          type: REGISTRY
        imageInitRepo:
          type: REPO_WITHOUT_REGISTRY
        imageInitTag:
          type: TAG

  clusterConstraints:
    resources:
    - requests:
        cpu: 1000m
        memory: 3750Mi
      affinity:
        simpleNodeAffinity:
          type: REQUIRE_MINIMUM_NODE_COUNT
          minimumNodeCount: 3

  clusterConstraints:
    resources:
    - requests:
        cpu: 1000m
        memory: 3750Mi
      affinity:
        simpleNodeAffinity:
          type: REQUIRE_MINIMUM_NODE_COUNT
          minimumNodeCount: 3

properties:
  tester.image:
    type: string
    default: $REGISTRY/tester:$TAG

  conjur-oss.ssl.hostname:
    type: string
    default: "conjurtest.myorg.com"
    title: Certificate Common Name

required:
- name
- namespace
- conjur.image
- postgres.image
- nginx.image
- conjur-oss.dataKey
- conjur-oss.persistentVolumeSize
- conjur-oss.ssl.expiration
- conjur-oss.ssl.hostname
- conjur-oss.serviceAccount.name
