apiVersion: v1
appVersion: "1.0"
description: A Helm chart for CyberArk Conjur
name: conjur
version: 1.0.0
icon: https://xebialabs-clients-iglusjax.stackpathdns.com/assets/files/logos/CyberArkConjurLogoWhiteBlue.png

