dependencies:
  - name: conjur-oss
    version: "1.3.6"
    repository: https://cyberark.github.io/helm-charts
    alias: conjuross  # aliased to remove '-' in conjur-oss. Downstream tools have problems without this.
