---
{{ if .Values.conjur.databaseUrl }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-postgres
  labels: &AppPostgresLabels
    app.kubernetes.io/name: {{ .Release.Name }}
    app.kubernetes.io/component: postgres
spec:
  ports:
  - port: 5432
  selector: *AppPostgresLabels
{{ end }}
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-postgres
  labels: &AppPostgresLabels
    app.kubernetes.io/name: {{ .Release.Name }}
    app.kubernetes.io/component: postgres
spec:
  replicas: 1
  template:
    metadata:
      labels: *AppPostgresLabels
    spec:
      containers:
      - image: {{ .Values.postgres.image }}
        name: postgres
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-conjur-data-key
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
    app.kubernetes.io/component: service
type: Opaque
data:
  key: "{{ .Values.conjur.dataKey | b64enc }}"
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-conjur-database-url
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
    app.kubernetes.io/component: service
type: Opaque
data:
  {{ if .Values.conjur.databaseUrl }}
  key: {{ .Values.conjur.databaseUrl | b64enc }}
  {{ else }}
  key: {{ printf "postgres://postgres@%v-postgres/postgres" .Release.Name | b64enc }}
  {{ end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-conjur
  labels: &AppConjurLabels
    app.kubernetes.io/name: {{ .Release.Name }}
    app.kubernetes.io/component: service
spec:
  ports:
  - port: 80
    name: http
  selector: *AppConjurLabels
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  labels: &AppConjurLabels
    app.kubernetes.io/name: {{ .Release.Name }}
    app.kubernetes.io/component: service
  name: {{ .Release.Name }}-conjur
spec:
  replicas: 1
  selector:
    matchLabels: *AppConjurLabels
  template:
    metadata:
      labels: *AppConjurLabels
    spec:
      containers:
      - name: conjur
        image: "{{ .Values.conjur.image }}"
        imagePullPolicy: Always
        args: ["server"]
        ports:
        - containerPort: 80
          name: http
        env:
        - name: CONJUR_DATA_KEY
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-conjur-data-key
              key: key
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-conjur-database-url
              key: key
